### ISSUE TITLE
npm start 提示程序报错了！ 大大开下是什么情况

### ISSUE THREAD

**Issue by AmazingRobin** [ahbool/vue-mix-pages#2]
win7  node v8.11.3

`
PS D:\wamp\www\vue-all\vue-mix> npm start

> vue-mix-pages@0.1.0 start D:\wamp\www\vue-all\vue-mix
> npm run mock && npm run dev

> vue-mix-pages@0.1.0 mock D:\wamp\www\vue-all\vue-mix
> npm run mock-stop && forever start ./mock/mock-server.js

> vue-mix-pages@0.1.0 mock-stop D:\wamp\www\vue-all\vue-mix
> forever stopall

info:    No forever processes running
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: ./mock/mock-server.js
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules
\npm-lifecycle\node-gyp-bin;D:\wamp\www\vue-all\vue-mix\node_modules\.bin;C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\wamp\www\vue-all\vue-mix\node_modules\.bin;%SystemRoot%\system3
2\WindowsPowerShell\v1.0\;C:\Ruby22-x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\
WindowsPowerShell\v1.0\;D:\TortoiseSVN\bin;D:\phantomjs;D:\NodeJS\;D:\phantomjs;C:\Users\Administrator\AppData\Roaming\n
pm;D:\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Local\Programs\Fiddler\RdRZ.log'
    at Object.fs.openSync (fs.js:646:18)
    at Object.forever.startDaemon (D:\wamp\www\vue-all\vue-mix\node_modules\forever\lib\forever.js:460:14)
    at D:\wamp\www\vue-all\vue-mix\node_modules\forever\lib\forever\cli.js:319:15
    at D:\wamp\www\vue-all\vue-mix\node_modules\forever\lib\forever\cli.js:162:5
    at D:\wamp\www\vue-all\vue-mix\node_modules\forever\lib\forever.js:412:11
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-mix-pages@0.1.0 mock: `npm run mock-stop && forever start ./mock/mock-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-mix-pages@0.1.0 mock script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-14T06_58_46_079Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-mix-pages@0.1.0 start: `npm run mock && npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-mix-pages@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-14T06_58_46_184Z-debug.log
`

**Comment by AmazingRobin** [comment]
解决了。刚才用npm install  ； npm start；  不知道为什么会错
然后改用 cnpm install ； cnpm start ； 正常运行了
估计是npm安装时 有些包体没处理好。
